### ISSUE TITLE
Fix Update Assignment

### ISSUE THREAD

**Issue by vuzDylan** [CaptainGlac1er/StudentHomeworkProject#19]

**Comment by vuzDylan** [comment]
Update assignment doesn't update it creates a new assignment

**Comment by CaptainGlac1er** [comment]
I was only able to reproduce when the assignment was archive then modified

**Comment by vuzDylan** [comment]
It happens every time but react will only render one object if two objects share the same key

**Comment by CaptainGlac1er** [comment]
Oh okay
